version: "3.8"
services:
  client-api:
    container_name: 'client-api'
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client-api.rule=Host(`widedelivery.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.client-api.middlewares=strip-client-api-prefix"
    ports:
      - '3000:3000'
    volumes:
      - feedback:/app/feedback
      - /app/node_modules
      - /app/temp
      - /app/dist
      - ./:/app

  client-apidoc:
    container_name: 'client-apidoc'
    image: swaggerapi/swagger-ui
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swagger.rule=Host(`docs.wd.mobile.localhost`)"
      - "traefik.http.services.swagger.loadbalancer.server.port=8080"
#      - "traefik.http.routers.swagger.middlewares=strip-docs"
#      - "traefik.http.routers.swagger.middlewares=docs-redirectregex"
#      why cannot use such approach as with own node?
#      because swagger try to search files, and here we need to not delete pathprefix,
#      so we shouldn't delete pathprefix for some files or smth like that
    volumes:
      - ./docs/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml

volumes:
  feedback:



